name: fuzzy_bolt
description: A powerful and optimized fuzzy search algorithm with typo tolerance and ranking.
version: 1.0.1
repository: https://github.com/Vishwa-Karthik/fuzzy_bolt
homepage: https://github.com/Vishwa-Karthik/fuzzy_bolt
issue_tracker: https://github.com/Vishwa-Karthik/fuzzy_bolt/issues

environment:
  sdk: ">=2.17.0 <=3.7.1"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
