name: fuzzy_bolt

description: > 
  A high-performance fuzzy search algorithm in Dart, designed for intelligent auto-suggestions, typo tolerance, and fast string matching.

version: 1.1.3

repository: https://github.com/Vishwa-Karthik/fuzzy_bolt

homepage: https://github.com/Vishwa-Karthik/fuzzy_bolt

issue_tracker: https://github.com/Vishwa-Karthik/fuzzy_bolt/issues

environment:
  sdk: ^3.7.2

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - fuzzy-search
  - search-ranking
  - text-processing
  - auto-suggestions
  - ranking

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
